


const data = {
 

    products: [
      {
        _id: '1',
        name: 'Asus Vivobook 15',
        category: 'Laptop',
        image: '/images/acer.jpg',
        price: '74,300',
        countInStock: 10,
        brand: 'Asus',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: ' Dell Inspiron 15',
        category: 'Laptop',
        image: '/images/acer.jpg',
        price: '43,940',
        countInStock: 20,
        brand: 'Dell',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Acer Aspire',
        category: 'Laptop',
        image: '/images/acer.jpg',
        price: '41,230',
        countInStock: 0,
        brand: 'Acer',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Asus Full HD Monitor',
        category: 'Monitor',
        image: '/images/acer.jpg',
        price: '21,700',
        countInStock: 15,
        brand: 'Asus',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'HP Pavilion',
        category: 'Monitor',
        image: '/images/acer.jpg',
        price: '97,000',
        countInStock: 5,
        brand: 'HP',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Acer Nitro',
        category: 'Laptop',
        image: '/images/acer.jpg',
        price: '1,10,300',
        countInStock: 12,
        brand: 'Acer',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;